---
name: Build Main

"on":
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [lint, test]
    concurrency: ${{ github.workflow }}-release

    outputs:
      release-published: ${{ steps.release.outputs.new_release_published }}
      release-version: ${{ steps.release.outputs.new_release_version }}

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          persist-credentials: false

      - name: Setup Java
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c # v3.8.0
        with:
          distribution: temurin
          # renovate: datasource=adoptium-java depName=java
          java-version: 17.0.5+8

      - name: Setup Gradle
        # yamllint disable-line rule:line-length
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3

      - name: Release
        id: release
        # yamllint disable-line rule:line-length
        uses: cycjimmy/semantic-release-action@8f6ceb9d5aae5578b1dcda6af00008235204e7fa # tag=v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: aki-bot[bot]
          GIT_AUTHOR_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: aki-bot[bot]
          GIT_COMMITTER_EMAIL: 103840025+aki-bot[bot]@users.noreply.github.com
        with:
          # renovate: datasource=npm depName=semantic-release
          semantic_version: 19.0.5
          extra_plugins: |
            conventional-changelog-conventionalcommits
            gradle-semantic-release-plugin
