---
name: Test

"on":
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Setup just
        # yamllint disable-line rule:line-length
        uses: extractions/setup-just@95b912dc5d3ed106a72907f2f9b91e76d60bdb76 # tag=v1.5.0
        with:
          # renovate: datasource=crate depName=just
          just-version: 1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: just install

      - name: Test
        run: just test
