---
name: Test

"on":
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Set Java distribution and version
        run: |
          JAVA_DISTRIBUTION_WITH_VERSION=$(
            cat .tool-versions |
              grep "java" |
              cut --delimiter=" " --fields=2
          )
          JAVA_DISTRIBUTION=$(
            echo "$JAVA_DISTRIBUTION_WITH_VERSION" |
              cut --delimiter="-" --fields=1
          )
          JAVA_VERSION=$(
            echo "$JAVA_DISTRIBUTION_WITH_VERSION" |
              cut --delimiter="-" --fields=2
          )
          echo "JAVA_DISTRIBUTION=$JAVA_DISTRIBUTION" >> $GITHUB_ENV
          echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV

      - name: Setup Java
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c # tag=v3.8.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Test
        # yamllint disable-line rule:line-length
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # tag=v2.3.3
        with:
          arguments: test jacocoTestReport

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
