---
name: Test

"on":
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Setup Java
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c # tag=v3.8.0
        with:
          distribution: temurin
          # renovate: datasource=adoptium-java depName=java
          java-version: 16.0.2+7

      - name: Test
        # yamllint disable-line rule:line-length
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # tag=v2.3.3
        with:
          arguments: test jacocoTestReport

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
